services:
  keycloak1:
    container_name: keycloak1
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev
      - --import-realm
    ports:
      - 2020:1010
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
      KC_HTTP_PORT: 1010
      KC_HOSTNAME_URL: http://localhost:1010
      KC_HOSTNAME_ADMIN_URL: http://localhost:1010
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_CACHE: ispn
      KC_CACHE_STACK: tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-network

  keycloak2:
    container_name: keycloak2
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev
      - --import-realm
    ports:
      - 2021:1010
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
      KC_HTTP_PORT: 1010
      KC_HOSTNAME_URL: http://localhost:1010
      KC_HOSTNAME_ADMIN_URL: http://localhost:1010
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_CACHE: ispn
      KC_CACHE_STACK: tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-network

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: localhost
    ports:
      - "80:80"  # Expose NGINX on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom NGINX configuration file
    depends_on:
      - keycloak1
      - keycloak2
    networks:
      - keycloak-network
  
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak", "-d", "keycloak"]
      interval: 30s
      retries: 3
      start_period: 40s
      timeout: 20s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge
